### ISSUE TITLE
The /mode command doesn't support specifying the target

### ISSUE THREAD

**Issue by maxpoulin64** [thelounge/lounge#223]
Currently, the mode always target the current channel. This works fine for most cases, but those constructs are also valid but unsupported:

* `/mode Max-P +x` (changing mode on self)
* `/mode #channel +m` (changing mode on other channel)

I don't think there are cases where one can change the mode of other people or non-joined channels, but we probably should.

**Comment by YaManicKill** [comment]
Note that this also should count as a bug, as it causes some issues.

I tried do to `/mode #pokemontrades +b` which is how you get the banlist for a channel. However, I get an error about the chan modes, and it sets +ms on the channel. So it's probably taking the name of the chan and using that as the mode.

**Comment by YaManicKill** [comment]
(note that doing `/mode +b` doesn't seem to work either, which means there is no current way to get the banlist on thelounge unless servers have another way to do it)

**Comment by YaManicKill** [comment]
Another thing related to this is viewing modes.

"/mode" or "/mode #channel" doesn't show you anything.

**Comment by xPaw** [comment]
Here's how hexchat deals with the command: https://github.com/hexchat/hexchat/blob/c698e13c0d3f8835581d1271371110da18827a92/src/common/outbound.c#L2679-L2703

**Comment by astorije** [comment]
Should be fixed by #679.

**Comment by fuzzy76** [comment]
#341 was closed as a duplicate of this, but the behaviour described by McInkay still persists. So either this or #341 should be reopened I guess?

**Comment by McInkay** [comment]
Yeah, it looks like #341 wasn't a full duplicate of this one. We can now specify the target, but it looks like we don't deal with the mode message when not setting a mode.

**Comment by xPaw** [comment]
I have a working prototype branch here: https://github.com/thelounge/thelounge/tree/xpaw/chan-mode-is
