### ISSUE TITLE
Clicking channel names with different case not handled correctly

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#363]
Seeing @YaManicKill mention (in #362) focusing channels on clicking them made me test that behavior. I sent these messages to my testing channel:

````
07:01	~dgw	test ref to #kaede for thelounge debugging
07:01	~dgw	also test ref to #Kaede (caps)
````

Then I clicked on each of them. Clicking `#kaede` (all lowercase) focused the existing channel buffer. Clicking `#Kaede` (the channel's proper name, with a capital K) did *not* focus the existing channel buffer. Instead, it inserted a fake join event and incremented the unread counter:
![screenshot 2016-05-30 07 07 22](https://cloud.githubusercontent.com/assets/164140/15649315/99454d5a-263e-11e6-92e3-17a3a3f505a6.png)

This isn't correct behavior. ~~I don't really agree with The Lounge lowercasing all displayed channel names anyway (especially because it leaves nickname case alone), but if it's going to be done it should not affect how the channels are handled.~~ Display casing is fixed in 2.0.0-pre.1 but the issue with clicking differently cased channel names persists.

**Comment by xPaw** [comment]
>  I don't really agree with The Lounge lowercasing all displayed channel names anyway
That should be fixed in master, is it not?

**Comment by dgw** [comment]
I have updated to 2.0.0-pre.1 and am still facing the issue with bugged click handling. The Lounge displays channels cased as sent by the server now, though, which has reversed which channel reference works properly and which causes the fake join & topic to be added to the buffer. Now, `#Kaede` does what it should, and `#kaede` fakes a join but does not switch to the channel.

**Comment by xPaw** [comment]
I can see that we are not focusing the channel on click correctly, however I am not experiencing the fake join you are describing. What network do you see this happen?

**Comment by dgw** [comment]
I'm seeing it happen on Rizon. Let me test on freenode, too.

**Comment by dgw** [comment]
Same behavior. The ZNC chanbuffer for #thelounge is non-empty, though, so I'm getting a complete buffer playback, starting with a join and a topic.

I can't get my desktop client, Textual, to exhibit this behavior with join commands, but I can get the same behavior in The Lounge 2.0.0-pre.1 by doing `/join #thelounge` (or any alternative capitalization I've tried)—join & topic event lines appear, followed by buffer playback.

**Comment by xPaw** [comment]
That's odd. I can't make it do anything unusual by doing `/join` for channels I am already in, no matter the casing.

**Comment by dgw** [comment]
Are you testing a network that's behind ZNC, @xPaw?

**Comment by xPaw** [comment]
Yep.

**Comment by dgw** [comment]
Could be a ZNC bug.

````
[13:25:36] <dgw> version
[13:25:36] <*status> ZNC - 1.6.0 - http://znc.in
[13:25:36] <*status> IPv6: yes, SSL: yes, DNS: threads, charset: yes
````

(I'm lazy about updating, what with 60 networks across 5 users)

**Comment by astorije** [comment]
> @thelounge/maintainers can any of you repro?

I'm afraid I can't repro either. Tested without ZNC, v1.5.0 (for now, until I fix my node upgrade), on Freenode.
I'll try on my laptop with v2.0.0-pre.1 later.
