### ISSUE TITLE
Messaging a lounge user opens a new window per message?

### ISSUE THREAD

**Issue by prologic** [thelounge/lounge#472]
Is this a known issue?

I have a client connected via Textual to a server and a Lounge user via Lounge's web UI.
Every time the Textual user messages the Lounge user a new chat window is opened with nothing displayed (just the source user/nick).

This is the debug logs from the ircd:

```
charla_1    | 2016-07-07 05:45:16,545 - plugins.Debug - INFO - I: [::ffff:96.82.78.101:61686] 'PRIVMSG lounge-user :test\r\n'
charla_1    | 2016-07-07 05:45:16,554 - plugins.Debug - INFO - O: [::ffff:172.17.0.1:37696] ':james!~textual@96-82-78-101-static.hfc.comcastbusiness.net PRIVMSG lounge-user test\r\n'
```

The I/O looks pretty typical to me. Any ideas? Is Lounge doing something funky with the receives PRIVMSG(s)?

**Comment by prologic** [comment]
Okay. I've confirmed this is a bug with Lounge.

The IRC spec actually allows private messages of the form:
```
:nick!user@host PRIVMSG target <message>
:nick~user@host PRIVMSG target :<message>
```

The later is only (the `:`) is required if the message contains whitespace.

**Comment by astorije** [comment]
Hey @prologic, thanks for the report.

Just curious, what version of The Lounge are you using? It would be great if you could try with latest stable version (`1.5.0`) and latest prerelease (`2.0.0-pre.4`).

**Comment by astorije** [comment]
Actually, I don't think it's gonna make a big difference, but testing against the `master` branch could also be helpful.

**Comment by prologic** [comment]
I'm using whatever you publish to the Docker hub. Let me check what that is...

**Comment by prologic** [comment]
> You're currently running version 1.5.0

Looks like the Docker image is a tad out-of-date? Do you publish on every git commit?

**Comment by YaManicKill** [comment]
It uses the latest stable version. 2.0.0 is still in beta.

Essentially, this will probably be fixed in 2.0.0, because we are using a
different irc framework, so we need to check if it's still an issue.

**Comment by dgw** [comment]
I remember having issues like this, but have not noticed this kind of thing since updating to 2.0.0 pre-releases. I'd wager that it's fixed with the switch to irc-fw.

**Comment by prologic** [comment]
FWIW I just tried to rebuild a new docker image on top of master with the following `Dockerfile`:
```#!bash
FROM node:4

ENV NODE_ENV production

ARG user=lounge
ARG group=lounge
ARG uid=1000
ARG gid=1000

ENV LOUNGE_HOME "/home/lounge"
ENV LOUNGE_DATA "${LOUNGE_HOME}/data"
ENV LOUNGE_SRC "${LOUNGE_HOME}/src"

# Create a non-root user for lounge to run in.
RUN groupadd --gid ${gid} ${group} \
      && useradd --home "${LOUNGE_HOME}" --create-home --uid ${uid} --gid ${gid} ${user}

VOLUME "${LOUNGE_DATA}"
RUN chown -R ${user} "${LOUNGE_DATA}"

# Drop root.
USER ${user}

# Install thelounge.
RUN mkdir -p "${LOUNGE_SRC}"
WORKDIR "${LOUNGE_SRC}"
ADD . "${LOUNGE_SRC}"
RUN npm install

# Expose HTTP.
ENV PORT 9000
EXPOSE ${PORT}

# Don't use an entrypoint here. It makes debugging difficult.
CMD node index.js --home "$LOUNGE_DATA"
```

Unfortunately the resulting instance fails to load several or more resources with 404 responses and displays "Loading lounge..." after a while "This is taking longer than expected"

:/

So I'm not able to test at this point!

**Comment by williamboman** [comment]
@prologic If you wanna run the docker image with a custom src I'd recommend mounting the source dir instead, like; 

```sh
$ docker run -v $(pwd):/home/lounge/src thelounge/lounge
```

Just make sure you've 

```sh
$ npm install && npm run build
```

on your host machine first.

**Comment by astorije** [comment]
@williamboman, `npm install` is enough, it already runs `npm run build`.
@prologic, if it doesn't go past the loading page, then you most likely need to run `npm install` indeed.

**Comment by williamboman** [comment]
@prologic I see. Then remove the `NODE_ENV` variable, or set it to `development`.

**Comment by maxpoulin64** [comment]
I'm fairly sure this is fixed in 2.0.0 due to the irc-framework update. Fixed a lot of bugs with private messages, self-message and all that stuff.

**Comment by prologic** [comment]
Look forward to it :) I'm still unable to build a Docker image with the
latest code for various build/install failures.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by xPaw** [comment]
@prologic Is this still an issue in 2.0.1?

**Comment by xPaw** [comment]
This should have been fixed in one of the 2.0 releases.
