### ISSUE TITLE
Longer nicks overflow on two lines

### ISSUE THREAD

**Issue by TheSonAlsoRises** [thelounge/lounge#577]
![tln5exm](https://cloud.githubusercontent.com/assets/8591366/17857067/9ef38dc8-6880-11e6-912d-9c381a30f9f6.png)

Long nicknames are going overflow a second line, which makes reading the conversation harder than it should be.

**Comment by xPaw** [comment]
Should be fixed by #523

**Comment by astorije** [comment]
@TheSonAlsoRises, could you check if this issue still exists on `master`? #523 was merged and hopefully this is not an issue anymore.

**Comment by YaManicKill** [comment]
It does still happen, just tested after #523 merge.

Fwiw, there are very few servers that support names long enough for this. Synirc is the one we both use for that.

I have a small css tweak that fixes it, but it's not perfect. Once [text-overflow: fade](https://developer.mozilla.org/en/docs/Web/CSS/text-overflow) is supported, I can sort this out in a really nice way, but currently it either involves a horrible fade with ::after, or the name just cutting off. Or using JS. Don't want to use any of these solutions.

```css
/* Truncate username */

#chat .message .from {
  overflow: hidden;
  white-space: nowrap;
}

#chat .message .from:after {
    left: calc(10% - 33px);
    content: '';
    position: absolute;
    top: 0;
    width: 30px;
    height: 100%;
    background-image: linear-gradient(to left, rgba(0, 43, 54, 1), rgba(0, 43, 54, 0));
}
```

**Comment by MiniDigger** [comment]
whats even the expected behavior here? should the nick make the column expand? should it be cut/faded? 

personally, I just yell at ppl till the change the size of their nick :D, we even have ban masks that ban nicks longer than 18 chars (I think thats the limit for lounge too) like '"??????????????????*". what I am trying to say with this is that this is really not something you should worry too much about, as its generally considered to be a nogo since other clients have such problems too. 
I personally would be fine with just cutting them off (we need some way to display that they got cut tho), the full name is always visible via the context menu.

**Comment by YaManicKill** [comment]
>whats even the expected behavior here? 

I expect it to fade out, but have a hover that shows the full name of the user. That's exactly the same behaviour as for channel names.

> what I am trying to say with this is that this is really not something you should worry too much about

I'm not worrying about it, I'm saying that it'll be an easy fix once we have the feature that is coming to browsers (currently in working draft) and I have a not-great fix that people can use just now.

> as its generally considered to be a nogo since other clients have such problems too

It depends on the server. On synirc, people don't tend to have a problem with it.

**Comment by bews** [comment]
So I guess this is how it should look, right?

![2017-04-30_05-23-19](https://cloud.githubusercontent.com/assets/3627488/25560790/a555a200-2d65-11e7-8f35-b51ae507835b.png)

Long channel names fix made in the same way, so I think we should do this again :smile:.  It won't be good for existing dark themes, though.
