### ISSUE TITLE
URL's getting mapped to whole word segment.

### ISSUE THREAD

**Issue by pinkeshbadjatiya** [thelounge/lounge#730]
This should either be a "text+URL" or the URL should not be detected at all. The current code detects a URL in the sentence but gives the whole word segment a hyperlink.   

**Build:** e9b118ea713fd44b41f022bb9e553c80e23fbb0e

**Example:**
![](https://ptpb.pw/4lQG.png)

**Comment by MaxLeiter** [comment]
is this fixed in https://github.com/thelounge/lounge/pull/699?

**Comment by Bonuspunkt** [comment]
yes result is
> so like..http://www.color-hex.com/color/564179

**Comment by xPaw** [comment]
@Bonuspunkt I think it's safe to assume that if the scheme ends with `http://` or other common protocols that it's a web link and not `like..http`.

**Comment by astorije** [comment]
This should be solved by #972. @pinkeshbadjatiya, can you test and confirm (on `master` only)?

**Comment by pinkeshbadjatiya** [comment]
Nope. Still not resolved
![image](https://cloud.githubusercontent.com/assets/14854424/25317547/53d21a7a-2898-11e7-94e8-067921dbb6e7.png)

**Comment by astorije** [comment]
Odd, that should have fixed it though, there is even a test case specifically for it. Are you running latest master?

**Comment by pinkeshbadjatiya** [comment]
Yes, I am running the latest master. (I am using the fork [this](http://github.com/pinkeshbadjatiya/lounge) fork).
I also tried to locate the changes from the PR in master but could not find 'em. May be they are moved to somewhere else or removed ?

**Comment by xPaw** [comment]
Use our master, the one you linked hasn't been updated in 10 months.

**Comment by MiniDigger** [comment]
@xPaw github reports it wrong. its updated with upstream master but he added older commits ontop of that. see https://github.com/thelounge/lounge/compare/master...pinkeshbadjatiya:master

**Comment by astorije** [comment]
It is definitely fixed on `master`:

<img width="192" alt="screen shot 2017-04-24 at 11 17 34" src="https://cloud.githubusercontent.com/assets/113730/25330372/b89adcc0-28df-11e7-9bab-9d2ec82c2330.png">

**Comment by pinkeshbadjatiya** [comment]
@astorije that is weird, may be merging messed up the commits. Let me check again.

**Comment by pinkeshbadjatiya** [comment]
ah, I forgot to build the new libs. Seems like the issue is resolved.
